version: "3.7"

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: love-frontend-image-mount
    volumes:
      - ./love:/usr/src/love
      - /usr/src/love/node_modules
    command: ""
    ports:
      - "3000:3000"
      - "3001:3001"
    stdin_open: true
    tty: true
